[build]
  command = "NODE_ENV=production gulp build"
  publish = "dist"

[context.production]
  [context.production.environment]
    HUGO_VERSION = "0.26"
    YARN_VERSION = "0.27.5"

[context.branch-deploy]
  [context.branch-deploy.environment]
    HUGO_VERSION = "0.26"
    YARN_VERSION = "0.27.5"
