baseurl: "https://studionock.com/"
languageCode: "en-US"
title: "Studio NOCK"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: false
enableRobotsTXT: true
enableEmoji: true
MetaDataFormat: "yaml"
googleAnalytics: "UA-93481692-1"

params:
  description: "Studio NOCK is an independent platform dedicated to architecture"
  contact:
    email: "info@studionock.com"
  adress:
    street: "Södra Larmgatan 7"
    city: "Gothenburg"
    country: "Sweden"

menu:
  main:
    - Name: "NOCK"
      Weight: -10
      Identifier: "home"
      URL: "/"
